# Install SnapClient on minimal OS

FROM amd64/alpine:latest

MAINTAINER Saiyato

RUN apk -U add git bash build-base asio-dev avahi-dev flac-dev libvorbis-dev alsa-lib-dev opus-dev soxr-dev cmake \
 && cd /root \
 && git clone --recursive https://github.com/badaix/snapcast.git \
 && cd snapcast/server \
 && make \
 && cp snapserver /usr/local/bin \
 && cd / \
 && apk --purge del git build-base asio-dev avahi-dev flac-dev libvorbis-dev alsa-lib-dev opus-dev soxr-dev cmake \
 && apk add avahi-libs flac libvorbis opus soxr alsa-lib \
 && rm -rf /etc/ssl /var/cache/apk/* /lib/apk/db/* /root/snapcast
 
# TODO
# Add page directory and update conf: https://github.com/badaix/snapcast/blob/1aee05cead72162d8e11d1f92d4d64e2379332e8/server/etc/snapserver.conf

EXPOSE 1704
EXPOSE 1705
EXPOSE 1780

ENTRYPOINT ["snapserver"]
